version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-7"
  markdownlint:
    enabled: true
  tslint:
    enabled: false
exclude_patterns:
  - static/redoc/**/*
  - node_modules/**
