version: "2"
plugins:
  structure:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-9"
  markdownlint:
    enabled: true
  tslint:
    enabled: false
exclude_patterns:
  - static/**/*
  - src/test/**/*
  - node_modules/**
  - CHANGELOG.md
