engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  markdownlint:
    enabled: true
exclude_paths:
  - static/redoc/**/*
  - static/voyager/**/*
  - node_modules/**
