version: "2"
plugins:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .js
        - .ts
  markdownlint:
    enabled: true
  tslint:
    enabled: false
exclude_patterns:
  - static/redoc/**/*
  - static/graphql/**/*
  - node_modules/**
