version: "2"
plugins:
  structure:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-7"
  markdownlint:
    enabled: true
  tslint:
    enabled: false
exclude_patterns:
  - static/redoc/**/*
  - static/graphql/**/*
  - node_modules/**
