on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-latest
    container:
      image: ffalt/jam-test
    env:
      JAM_DB_HOST: postgres
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  build:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build:deploy

      - name: Generate Releaselog
        run: |
          npm run releaselog

      - name: Deploy to Release Branch 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: release # The branch the action should deploy to.
          folder: deploy # The folder the action should deploy.
          clean: true

      - name: Create Release Package
        run: |
          cd deploy && zip -r ./jamserve-release.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./RELEASELOG.md
          name: ${{ github.ref_name }}
          files: |
            ./deploy/jamserve-release.zip
