name: testbase

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ffalt/jam-base
    steps:
      - uses: actions/checkout@v2
      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '12.4'
          postgresql db: jamtest
          postgresql user: test
          postgresql password: test
      - run: npm ci
      - run: npm run test

