name: testbase

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ffalt/jam-base
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
