name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ffalt/jam-test
      options: --user 1001
    env:
      JAM_DB_HOST: postgres
      NODE_ENV: development
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26.x
          package-manager-cache: false
      - run: npm ci
      - name: Try to build
        run: npm run build
      - name: Test with coverage
        run: npm run coverage
        env:
          API_SPEC_TEST: false
      - uses: qltysh/qlty-action/coverage@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
