name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ffalt/jam-test
      options: --user 1001
    env:
      JAM_DB_HOST: postgres
      NODE_ENV: development
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.x
          package-manager-cache: false
      - run: npm ci
      - name: Try to build
        run: npm run build
      - name: Test with coverage
        run: npm run coverage
        env:
          API_SPEC_TEST: false
      - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
