name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ffalt/jam-base
    env:
      JAM_DB_HOST: postgres
      NODE_ENV: development
    steps:
      - run: git --version
      - run: apt-get install git -y
      - run: git --version
      - uses: actions/checkout@v2
      - run: git log --pretty=oneline
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
