name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ffalt/jam-test
      options: --user 1001
    env:
      JAM_DB_HOST: postgres
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm install --os=linux --cpu=x64 sharp
      - name: Try to build
        run: npm run build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jamtest
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
